apiVersion: v1
kind: Service
metadata:
  name: skaha-notebook-svc-${skaha.sessionid}
  labels:
    run: skaha-notebook-svc-${skaha.sessionid}
spec:
  ports:
  - port: 8888
    protocol: TCP
    name: notebook-port
  selector:
    canfar-net-sessionID: ${skaha.sessionid}
